// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;

namespace DogBreeds
{
    public class ConsumeModel
    {
        public static ModelOutput Predict(ModelInput input)
        {

            string modelPath;
            MLContext mlContext = new MLContext();

            try
            {
                modelPath = AppDomain.CurrentDomain.BaseDirectory + "MLModel.zip";
                ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
                var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

                ModelOutput result = predEngine.Predict(input);
                return result;
            }
            catch (Exception e)
            {
                System.Windows.MessageBox.Show("Model.zip file missing. Please choose another.", "Missing Model File", System.Windows.MessageBoxButton.OK, System.Windows.MessageBoxImage.Error);
                modelPath = FileNameGetter.returnModelZip_filename();

                ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
                var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

                ModelOutput result = predEngine.Predict(input);
                return result;

            }
        }
    }
}
